"""empty message

Revision ID: 448562cda3da
Revises: 0e2d41f783e0
Create Date: 2019-04-07 10:59:47.665393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448562cda3da'
down_revision = '0e2d41f783e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
